version: 2.1

jobs:
  build:
    docker:
      - image: node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Build app
          command: npm run build
      - run:
          name: Test app
          command: npm test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build